name: Generate streak stats

on:
  schedule:
    - cron: "0 6 * * *"
  push:
    paths:
      - ".github/workflows/streak-stats.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: DenverCoder1/github-readme-streak-stats@main
        with:
          options: user=Romherre&background=FFFFFF&border=D0D7DE&stroke=D0D7DE&ring=24292F&fire=FF6600&currStreakNum=24292F&sideNums=24292F&currStreakLabel=57606A&sideLabels=57606A&dates=57606A&hide_border=false
          path: profile/streak.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit streak stats
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile/streak.svg
          git commit -m "Update streak stats" || exit 0
          git push
